apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: development
stringData:
    username: ENC[AES256_GCM,data:6Ltb7tCjXCQ=,iv:vSXiLQKnfksNOkpQECX2OopAz8eEvzWSVtVBBsJVYx0=,tag:S/MuOBw8SNbOmRbM9l4CsQ==,type:str]
    password: ENC[AES256_GCM,data:VFBP2J8bKd3GPWlN5xNJ,iv:T++ftOJzt93F7TL+BXE8dHQMM44BvqzDytn71+TZbFU=,tag:VdHO5FAobLL0UYXw3GmyeQ==,type:str]
    email: ENC[AES256_GCM,data:pQ9QhR1BfBNmTFNj7lx8+hy+,iv:pDkmxOLAgA6eE/jAALsp4MV07RYjFnwBdpJ/ajbQ+iw=,tag:ZgmpBWbSdch5KtXlbKVFwg==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUEVNR2NnVHZlWVdqaWd4
            TFNQcEQrMldXa2hQQVdyOGJWVzFrT1dZRHhNCmhrZkNmbEZZMlM1czVQd1JTRzdR
            LzlDNk1pMndZdEFTTG1WdmN4SDIvbE0KLS0tIDg1TUtWWk5MLzhIZjZ6ZUVvdkFj
            K3I4Z3QzQVlvTVFpYThGSzdVSGloR2sKKfGHOfC8bA5l4o846bKMpko0gxgGlipg
            GuPAKSHXAn41nzpowyNt/lUYF0iB60he8/WZTuLIMwJztvxMDJoTeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-27T22:21:51Z"
    mac: ENC[AES256_GCM,data:DfI+lXQtvB5DFFmzp/eVQxo2pHZgOtlQ6RW+xc5DhYLcze/fJjm0jfA2tjS0bfZcjCEE04cXXnNIRnytw3kl6i9KUqNTUKnW3y863QEgdIGjtqz+zNWp3eiur5T2N6O8P+iUPbsKe5Qv8ROI0WQ/bmFgw99Ht0fgRVv/66/8Uz4=,iv:eot9k+fK9r7shSI4bfvXDMidsuN2+r9W1i3cftnpJ1Q=,tag:GLmeVagjJb7VrsdHjEsM3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
