apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:8A4xc9YamYegcA==,iv:MUvSMJs1bhWWXEp66YRDTlBm2DH9Ug0TcLCoaOHB1+I=,tag:6MCYqD2/W3/Fd31EpOEXZg==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:oH9KqAc7o9jLzk0gqfo=,iv:NCU4wXUJ16tl0tAr5sWCMeryo8nZlxrSrktdXrrKpNU=,tag:Z2Q+41QmKxI507/5g2pvQQ==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:T2BLSTob2AbMgr48wo5hpmkpqFM=,iv:jW5tanN0neZ51RG7zQtzMyTaTcSK9/9korvdUeW3ba4=,tag:8ysPHF7XXZ8bWU2UQ58a1Q==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:1bkx2rzTtIrbDqnnivMGJxVLb2ULY4vYSLdbmxtVx7FNH9Rx3O6fOVo8BIVjWbJAVv1KkF7TYllXLDZLS5166g==,iv:vSDsBshm8swrzDUYjz50eyFh8Zp64Z5pN9RNYBiAotA=,tag:Yd7QFZ2jprhRWLijp1fhcg==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NStjMWFjemx6SnJwMURO
            bGlYV1pCWTlsK2dzeDE0NWE0WjZHUm5YSVZ3CjM0NDY3TytRdncrTE5EeTcwZDNs
            bnVxTnNIUS9MdGIvcmFyT2JkYWlJWGcKLS0tIEJWdEtwdlJ3THhueEZySnJkenor
            azJHWTY5YTVvZ1IxSnZPTitrMldpb0UKiXp9Cltaqnn+uyR1QKjYfpX5Mqxn68IF
            uH7sJr2wvTNtVytRn3TaQKFiuiTxxE/xhPhlMXKupCU9RWU1/kZopg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T13:01:54Z"
    mac: ENC[AES256_GCM,data:WP39tF50wCn05TWHtEx3ITHHpiQt6dIyS8B1qtio8OJmwCzFSDG8LI1mV7+Un6/XvEmTI+tTXuru8pjI+SyesJRQ2bDjhRRsMul09DyQgaMscjHJ1pZ2rOnEunilmVPqRByMXUKTlxM6611PB5g7w0q2+AnuAToj/xLcgZcOweI=,iv:YPi1iiKZyY0dUi1wGCR4u6TBKj+h/2ykTS/Pipi7ozA=,tag:L091dUFPy6X9xCQRRZ7i+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
