apiVersion: v1
kind: Secret
metadata:
    name: envoy-oidc-secret
stringData:
    client-id: ENC[AES256_GCM,data:WeGxLmYBZoZR2Tsjex5nSMhIrfHTaEhwpiVypgT4/84zj8Xh,iv:JsYb8vOWXR2dKbbav2j8kPSY5qAL+AOxDNVCah8Ln0g=,tag:BwEGGh8QAKzYBsQGEJW50A==,type:str]
    client-secret: ENC[AES256_GCM,data:kkRBPq4ShDZ2E+LtMfPmc2ctymY17nHl+Yx6vGPKVZI=,iv:Z/oqQr4ilRYBBk2nR86hpSyg1w8VYHhkXH5JBQJPSTY=,tag:WlMsf7BvUCczlRPxF9jlHA==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTzFTZ09pajNISDl5VmJG
            K3VkWTlGUm95S2dsWldJMnB6Rm9NVTVSOVVJCi8yVTdRdGh0NUYvTkI0SC9uOFpN
            T1V1cHQ4UXIvWlZtL3V0TUtWeXI3V28KLS0tIFE5TzNxSGpyVDhrZjFUUTBrblk2
            c1NYRkJmOW5QclVpR3VJV2hZcFFPakUKh3A8SRcvzPRHVjfLrm7XkjvjJ2Pn445O
            kqodsbiEuwly8U9I9xq7KImS4hORCRepxvo7ZZX9gbfiyMDwZyrnFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T08:28:11Z"
    mac: ENC[AES256_GCM,data:IcWaGL35llt1FKV2GKeMBbf9To2ncAcQOh98Mkl8DNW2LQDT4u1QHCbAIrJgIYCCHH0RRPni5ZRxiIchjinaEpxDLOKEnDagsbo//necNoVzTfLrP9V848/KCo8/2Br2UfXa5RHPkEqIAt3hBwYrEkPaWtC6M6ml+TL6RL9V6U4=,iv:1ak4TgTXPbgCJHfdaMUZJcps96CG9Zwwtom61q6ru74=,tag:k8DF+Pj10nZJQcosSn1iAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
