apiVersion: v1
kind: Secret
metadata:
    name: freshrss-secret
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:TS1PdnBI4pF7Nv3dxH7kFZYbvFXvdI6SeK5QpVmGpDCWaLi2,iv:5TT4qtjzbP/CJbY0vScv7Wdtsey3eikpN/PS0v4q2EU=,tag:NYmmp3D7WHx75qTjBqdNRQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:muAcqdve+ESUM1omHO8ewIXHZamo1q7+zDPYOoqOQ54=,iv:RlfE+CQoz6chK8OisbWqL3bOfPXYlX35pAcG3dlbdJc=,tag:RuCbcVRIc4mIZ6ztqBn4dw==,type:str]
    OIDC_PROVIDER_METADATA_URL: ENC[AES256_GCM,data:hW+sYcTSQerfQirC6EbbAJecgg0ABuMRrtKVxreMIT+V3xgHVEid6utvVgPEzv+uz1WR7nrPEFo=,iv:zIgj0cP0OiprEYr9u3Sla3N95aHg7xJpsqaBJuOOxos=,tag:3MDRZPwavn1pD448/Tm+lg==,type:str]
    OIDC_CLIENT_CRYPTO_KEY: ENC[AES256_GCM,data:hXjg0asv3grNjXudLl5bCqMzaaoK3zFwqGKvKNp/YEBwcEK/v30v6PZ4u0O6AEMyBthoGEPGkGZgF85vQyEUYpK/jJrWXl/tJiWS5lcX1Xr3P4ynfsfRQg==,iv:toI05BHZcbBfWtN/KX+RmTNspkbFKcYR20kZ2qQ+pLE=,tag:OezfaI5ZVqmGYL0UZqDU0g==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTmFpUFIyWkozeEt2Yzhu
            eEovTHBTajdadEtoczgvZnJwdU9qRzNkbnpJCjA3RWZreVpGY0NsbmE0a2R3Nzkw
            cVlYWWlqVDhuZk92MVd0LzB5MmdNV2MKLS0tIERBUTl5S2M0QXNmTGc2aVNRUzVP
            R0N2dkdvWFJhTE9vNngrMXArcG5KOVUKwFERWLldwgQef/vgB0nG9qB23IeuyE5L
            dxgICK2T+AhlikMSMHYukse+C94/RVdq+tOhNulTtg1W6eMibxouVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T21:59:35Z"
    mac: ENC[AES256_GCM,data:iMHo/unR7M6xt2vOc2YJRnIP854eiR8CjnFWMF1duhF7/Z95q8nEm3U9ooH5eA2ziTr+RRiZfIkq7/wx27+kNX7WCHlY3o6THPE9DbqCcTBF1X3LR4Ps0/URknEHdNeORcvQJULJbcTuuE+55h9H9WrBoEyM9KJD7t02oNX1vNU=,iv:rBnzSkejY3a6AoEJc1t9dRi5DYGCzB8IszatXEr9OKM=,tag:J4VO9mm/pUlHik0I3foUiA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
