---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy

spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: ntfy

  values:
    controllers:
      ntfy:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: binwiederhier/ntfy
              tag: v2.16.0@sha256:115357a63dd35e3d08ad03c93ade7d7eef63761726572b809da13f2999f1958f
            args: ["serve"]
            env:
              TZ: Europe/Berlin
              NTFY_DEBUG: false # enable/disable debug
              NTFY_LOG_LEVEL: INFO # adjust log level
              NTFY_BASE_URL: https://ntfy.offene.cloud # add base url
              NTFY_BEHIND_PROXY: true
              NTFY_CACHE_FILE: /var/cache/ntfy/cache.db
              NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
              NTFY_AUTH_USERS:
                valueFrom:
                  secretKeyRef:
                    name: ntfy-secrets
                    key: auth-users
              NTFY_AUTH_ACCESS:
                valueFrom:
                  secretKeyRef:
                    name: ntfy-secrets
                    key: auth-access
              NTFY_AUTH_DEFAULT_ACCESS: deny-all
              NTFY_ENABLE_LOGIN: true
              NTFY_ATTACHMENT_CACHE_DIR: /var/cache/ntfy/attachments
              NTFY_WEB_PUSH_FILE: /var/cache/ntfy/webpush.db
              NTFY_WEB_PUSH_PUBLIC_KEY:
                valueFrom:
                  secretKeyRef:
                    name: ntfy-secrets
                    key: web-push-public-key
              NTFY_WEB_PUSH_PRIVATE_KEY:
                valueFrom:
                  secretKeyRef:
                    name: ntfy-secrets
                    key: web-push-private-key
              NTFY_WEB_PUSH_EMAIL_ADDRESS:
                valueFrom:
                  secretKeyRef:
                    name: ntfy-secrets
                    key: web-push-email-address
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 150m
                memory: 150Mi
              limits:
                memory: 300Mi

    service:
      app:
        ports:
          http:
            port: 80

    route:
      app:
        hostnames: ["ntfy.${EXTERNAL_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https

    persistence:
      auth:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: ntfy-auth-pvc
        advancedMounts:
          ntfy:
            app:
              - path: /var/lib/ntfy
                readOnly: false
      cache:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: ntfy-cache-pvc
        advancedMounts:
          ntfy:
            app:
              - path: /var/cache/ntfy
                readOnly: false
