---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app calibre
spec:
  interval: 1h
  timeout: 5m
  path: ./kubernetes/home/apps/media/calibre/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: volsync-kopia-secret
        kind: Secret
    substitute:
      APP: *app
      VOLSYNC_CLAIM: calibre-data
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_GID: "1000"
      VOLSYNC_UID: "1000"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
