apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
    namespace: selfhosted
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:TuRwWgtNMU3tPDICEFQv8GGVFkl3RDYeQQfNCI8tFbSL5fje8nmle0wRzJgFs7AC1I5vQlNfrxan0E08kFRExNW4QHnRtBJQfq94KZ4qXcNnMPblOqeZaUGexyhoyjr0qcNHkKISHn44/KHUr/jyPdSgWljBWQ==,iv:5XK/Ng1QDJD+NmeZOHzH2o1AriwJ2PH0sUQ9LYQWpFc=,tag:BsIZoWTfhvLNHPgvC9pYvA==,type:str]
    SSO_CLIENT_ID: ENC[AES256_GCM,data:n6dpvEWPncEX81EHvkopYbCHp37zqSzqT6bhDnv3WNnEYUcI,iv:7PeRNltR7Yki0qJm/HdTeMforK2/gKDJTBdzHVs2QrI=,tag:DhUJ17tHOTN04SZ6KsRcPA==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:eSAyooIMNNsNGn7z6Sp009A6l2/dKGbr4ERQ/QopE28=,iv:wsPPVhB6KxO33+1NeAU9XYBOYXCsbD6ZridP3sobsW8=,tag:GcU0tX5qsSMfyLwZO0hS4w==,type:str]
    SSO_AUTHORITY: ENC[AES256_GCM,data:AEn9id2OGYyirQPd2GgOtoF5iFEfofI=,iv:MVdNORImy/7f523sIZWAK0jowXokW9vl4z06uta4TTM=,tag:N+4XpxhZWkQ00HmeYSNFHw==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVWM0ZGo1b3Y1RlN5ZG4w
            N3BXb3Y4QzdMcjdQZmRERW00Ry93UXFYOVZrCjBHRE9uUXpEaVBmMFFmV2lGclY2
            SFhpTnc1Rk5uSWxubWVqOWN0QlN2SDgKLS0tIDAxOGFlMDhrSDBYRUJOOFMvclhp
            cnQ3UEZHU2c5dGw2SFc1YTJWeFJ1RUkKFP2aB9YpAfoopTEPtE4lJJ5UuiwYmyA7
            zbRUwKNpUVZKDPaOfwUXiOI5BTGDYW6VrsldScgNoNgJ/xFFDDHGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T23:04:27Z"
    mac: ENC[AES256_GCM,data:l9FwwTMjLa/u0qTsrT56cpsp/Ew4Xnn7SH8tpcTb7WMzRsLIybMFiJsFlNaQodxf89/BcntHjJIibOFabzIFMMNVP/rUENt1+imyCn2DexmkRl70jlGhDjFb6x46koMgCVH71aYSadyGtwcaz8ZxT6zzmfP8S94031Lja0mZtRc=,iv:tb6A4ITioo7sdHlJOwfOpwrAzpvDt2dR/6/vWd7qiGA=,tag:4SIRhbgpmKEZ1w/kW0KaSw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
