---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-netcup
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager-webhook-netcup
      version: 1.0.38
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-netcup
        namespace: flux-system
  values:
    groupName: com.netcup.webhook
    certManager:
      namespace: cert-manager
      serviceAccountName: cert-manager
    image:
      repository: ghcr.io/aellwein/cert-manager-webhook-netcup
      tag: 1.0.38
      type: ClusterIP
      port: 443
