apiVersion: v1
kind: Secret
metadata:
    name: netcup-secret
    namespace: cert-manager
stringData:
    customer-number: ENC[AES256_GCM,data:GWwDug8Q,iv:n7iZKyZDVSCJy3pK88Is8qsltdGQ1LITdN+Kr508V1I=,tag:oXLd7SVh16NEa9r2Jvi2wQ==,type:str]
    api-key: ENC[AES256_GCM,data:KxA+C/P1RpPQ7uCqajDfUJcCcDBzLtVL5RFssuDxoDzMNxpGrnHpZiTbUYttvR3FiGo=,iv:PV/vpJPg7zY4lqCnRnAHFYy+Elc0MePpHtP0GBIrw6o=,tag:Qq1Nl/kni3CUFRccxYvO4w==,type:str]
    api-password: ENC[AES256_GCM,data:ap5vHoKcOsw0fnABnCcqeXIx8yTMWDwDb5+TUtfDQym80ZjJh/w0w1i7K2i6/ffAHLc=,iv:qsHyd05a6tyYcZNl/JVoZ73ZYsaJb2ZE4v+F6hXNXq8=,tag:IxZy3OzNpDqVLx55ltyTBw==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoR0owMk9wQ096alRDdk9u
            ZWxSN2RxMmkzOEs2UTkxcCs3Si9NRGlhZWg0CjQ3aXlvTEs2R2xiZzIvVmhUa1Zz
            NkoxeUJNQWM3ZEwvV3JWWHZyMmRPTncKLS0tIEFyY0tneTlMampvVHA4SWZRQTRO
            S1hJcFVuanVOTURhUU4yQ3FLZjVqek0K+sDhkZ+zZH0q/TM+UEGr3jKUFXkFDo0a
            acWCYslRKbm1umw7y+ISByjTDZt5VvWrwB/MsSKwpenoZ25Ny/zHFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T21:58:33Z"
    mac: ENC[AES256_GCM,data:st3imkxiGMMP2GjO6t2MvmQm8q4nxflouO9b2NKCw3ILuGoh7XadxNvnUfyBSPuE6/WZ03a8+Tj8z4n8Z6MdBjgWBace1ssF0WGzx1LVKIfwBvfWE935dtztZhWNu6ja8xCumscGsXq4sHWB3K0r8U0JLrC4BZ2I1Gzhky6p928=,iv:PiHRqJ61aiU8oVL3ft9045Wb1OBw89McmpNxa6o6aOI=,tag:9cI/pTKC259I8T8Co8uHkg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
