apiVersion: v1
kind: Secret
metadata:
    name: configarr-secret
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:InMXh6mHj3iRQsVbhCQlHrCK0dCOvQerksDCipLDdCI=,iv:JwypOAfg/Zz1R2cNyoNipROolOJgS6J2j7YvwVe89ds=,tag:v6bMbVHR41B2J73CZkh6Yg==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:hxpEcRTyN0Ex7otff0IwBgM/FEE/mXXVJceNHgIph+A=,iv:UaL0Zc9L0qvQLyc1+/6UIhFFLP3f8TDPpcCr33/yQUo=,tag:3egomnjqx6QEd0ITXedXBg==,type:str]
    SONARR_ANIMES_API_KEY: ENC[AES256_GCM,data:T0qqJAQiSP3uRZfXIA0DdV/Vu0yRvOGmwwgbHCARbLE=,iv:h9CbTeGanqnnatOTAmEBPBaVhZgw0GJrNkYiRbW0940=,tag:C8i/6s/4PN9JHLHBHushHA==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTzFTZ09pajNISDl5VmJG
            K3VkWTlGUm95S2dsWldJMnB6Rm9NVTVSOVVJCi8yVTdRdGh0NUYvTkI0SC9uOFpN
            T1V1cHQ4UXIvWlZtL3V0TUtWeXI3V28KLS0tIFE5TzNxSGpyVDhrZjFUUTBrblk2
            c1NYRkJmOW5QclVpR3VJV2hZcFFPakUKh3A8SRcvzPRHVjfLrm7XkjvjJ2Pn445O
            kqodsbiEuwly8U9I9xq7KImS4hORCRepxvo7ZZX9gbfiyMDwZyrnFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T17:31:27Z"
    mac: ENC[AES256_GCM,data:+M6Q1D6vXr8iBEh0i2aIa/+HE2rkAix4mqak7fDh640HRwJP9bFnT51/1Bn6h+uGGnHYQnIKpqSwKt4dfZLsgrrFddH/EY9WLXCQMuPeqQxj53Vm4emtU/xlk9AGIInQx6twu/oGoG/4rfqwMk0z7k2i1KSuYPvfv3kC9unrnJU=,iv:rbbl9D2MP7nz46PcOD8hNNYLZZgEWMyxQWF7KLK3SBQ=,tag:WzE1tPI5ju2twr1Eozg11g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
