---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${VOLSYNC_CLAIM}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: ${VOLSYNC_CAPACITY}
  storageClassName: local-hostpath

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}-postgres-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-hostpath
