apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
type: Opaque
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:hZRy1wdHog==,iv:P18lZABT0rO7onKJo04n1ok1NbmR9AZZsxAaA83yhWA=,tag:JBjs461GJ1gEaIVNy9ydvQ==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:J5zRtbJJluaed3NbNN8AgX/LJy7Emxk6tZ8XPxiH01vlpxqYIzJwVNRjGasVdSZ26hOsv/gIXGfFMfdD,iv:VX6jHE/U+XH8n2LctA0s1hKh8E9iB4w7j/aL36/duOc=,tag:ZMtp529obWzM+8Ue9o3U7g==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL3JJTXlYRWdwS0xwRXRQ
            Z0F1MTU3OGk0bGFYUW5hSTBuMXloSkREUkJZCmhDNFN6RmZWL2cySmxDUXR2K3E0
            eHZXdlBBd2lvRlhUelFaNUZVa3cyd1EKLS0tIEJJcGh2UzZOaXN5cGJUVjBvMS9V
            aUY2K1g5d0g5dVRFK1MzSFNzZDBNaE0KVAQy/yiLtCbfoFYH5FjPluoVMqFFc2rD
            Tygd6771r+vW7XanPbDaFtCPyREocArFCFpFH6t9Kz+/35YaAbAsRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T21:32:25Z"
    mac: ENC[AES256_GCM,data:djSXuXC4m2HIHkFpzs+XYEyd4hx7h7cBXokxJ4mmf7kTlpV7u4sS335/Mhh43k57BgAL3AoCzF4NxCjn/MduwXQjFxV4aX42aVu2CR1Yrd9tpb/DKUlTiLg4AGljBji4T6m2dJauDzh9ZYwxBglYfHX/av0MGSDmsy755t+O+Aw=,iv:RSsQ3SoDCuZ2CZUml4g1+CRI0TdnzcHegSaTvBeSQ0Q=,tag:z2dTNj1grESowWXOydEYxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
