apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
type: Opaque
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:hZRy1wdHog==,iv:P18lZABT0rO7onKJo04n1ok1NbmR9AZZsxAaA83yhWA=,tag:JBjs461GJ1gEaIVNy9ydvQ==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:3i93BsKkhKSYoo3IF5kJ199B6xSAeJh/FaLGyIH77niWlpvH4TtWdHYmHaTl8UVjPb1DI8W7N4gE7Pk8,iv:3fEp+rfTbMOvjm49mfVk8mCP7V427TdvkcgV7qyO40U=,tag:+Y5CIRVnKJATqPPmaIBlrg==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL3JJTXlYRWdwS0xwRXRQ
            Z0F1MTU3OGk0bGFYUW5hSTBuMXloSkREUkJZCmhDNFN6RmZWL2cySmxDUXR2K3E0
            eHZXdlBBd2lvRlhUelFaNUZVa3cyd1EKLS0tIEJJcGh2UzZOaXN5cGJUVjBvMS9V
            aUY2K1g5d0g5dVRFK1MzSFNzZDBNaE0KVAQy/yiLtCbfoFYH5FjPluoVMqFFc2rD
            Tygd6771r+vW7XanPbDaFtCPyREocArFCFpFH6t9Kz+/35YaAbAsRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T15:06:42Z"
    mac: ENC[AES256_GCM,data:GmnJV9hd3UyX5Z9T3KBRkdXa0yXY/ikFLHkNvfD0VSfkQaqC1/ad4lAgdOwmpRZlepgZC2sEH4elzWP5e+qIdmSaVtr67ygz3iuNLaLoCwaXS2xFheQMhbMYOGR+4WkVFTIXmUCi4roxrIjo144s1aGNmMsdl3Q+/EYxWhhuyKI=,iv:QfZgSq5PS+joBT3M9y78OOCKkixryslc/wvt4lsI59U=,tag:g9elSaxwftF4lK8m34a90g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
