apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:rcTSCoeUIB9StvFKDv17CYrLFX+6gNd++XiEDNDzysPYb5dBk20aYVAK5mZfQsmmYgreAYibrN7E3f2xJupMR144l2m8PwH/nUE2POieE7JSfR7VDcWNKA==,iv:fb0J6Atls9NAZgH1+qXxk8LVQRo0CWAmyqc0c5JcOx8=,tag:Iu+ZNX/cgQTsgQGOlv3lsw==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MVhlVmZ3Mmw2VTBoc25K
            WDIzRG1tWVJjbjBZNFlDQWlzak9yTG9PM2dBCmNKTHMxU1pxN05DN2J1aFVmSm9K
            ZmljaVZhYUtOcnRLdEJTZFFCVHlINzQKLS0tIFFTZW1Wc1FUNFZlR1VkRkRuN2tO
            VFQ5TjBISjBFUmNNZlZDN25UZ2NSRjgKsWLRPiBufELS7X8bxxrw3llGFvfUotwz
            DQ5ahEy/pertb2J8Z1qw/WQwZ+t5gMBJPvTexs+65yyIL8ToPJ8OCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T21:13:49Z"
    mac: ENC[AES256_GCM,data:9VxNJG3WQ+ra/hIxNwXiKaIIYggjjPhztjAJqQKeXFGbPk+k6GRnRwraG0JRHtmQof+hIArpJRz2oZfhBwwQJHlB1j1L5aTOmIU2KgMwxEgijC0t8IxIvCiQlQBwsdNguW7Un2yVZAM3xk0DsE6k9g6ef6iOhJvfHcvoroNxB/Q=,iv:evfDukm4ry/9Riv/xc9RzUoj68GwJmBQ3omGmjFv+ec=,tag:MTuEwaJHvGePV/LIiovSfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
