---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tandoor

spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: tandoor

  values:
    controllers:
      tandoor:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/tandoorrecipes/recipes
              tag: 2.5.3@sha256:7ce6534c9ab0e471fd0f08add67e871b9173fb580c2f86294c3ead025603a3d7
            env:
              TZ: ${TZ}
              DEBUG: 0
              DB_ENGINE: django.db.backends.postgresql
              POSTGRES_HOST: tandoor-postgres-rw.selfhosted.svc.cluster.local
              POSTGRES_DB: tandoor
              POSTGRES_PORT: 5432
              POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: tandoor-db-secrets
                    key: username
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: tandoor-db-secrets
                    key: password
              ALLOWED_HOSTS: rezepte.offene.cloud
              CSRF_TRUSTED_ORIGINS: 'https://rezepte.offene.cloud'
              TANDOOR_PORT: 80
              SPACE_AI_ENABLED: 0
              ENABLE_SIGNUP: 0
              EMAIL_HOST: smtp-relay.network.svc.cluster.local
              EMAIL_PORT: 2525
              EMAIL_HOST_USER: ''
              EMAIL_HOST_PASSWORD: ''
              EMAIL_USE_TLS: 0
              EMAIL_USE_SSL: 0
              # email sender address (default 'webmaster@localhost')
              DEFAULT_FROM_EMAIL: no-reply@${MAIL_DOMAIN}
            envFrom:
              - secretRef:
                  name: tandoor-secret
            #securityContext:
            #  allowPrivilegeEscalation: true
            #  readOnlyRootFilesystem: false
            #  capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 2Gi

    #defaultPodOptions:
    #  securityContext:
    #    runAsNonRoot: false
    #    runAsUser: 0
    #    runAsGroup: 0
    #    fsGroup: 0
    #    fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: 80

    route:
      app:
        hostnames: ["rezepte.${EXTERNAL_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: tandoor-data-pvc
        advancedMounts:
          tandoor:
            app:
              - path: /opt/recipes/mediafiles
                subPath: mediafiles
                readOnly: false
              - path: /opt/recipes/staticfiles
                subPath: staticfiles
                readOnly: false
      tmpfs:
        enabled: true
        type: emptyDir
        advancedMounts:
          tandoor:
            app:
              - path: /opt/recipes/cookbook/static/django_js_reverse
                subPath: django_js_reverse
              - path: /var/lib/nginx/logs
                subPath: nginx_logs
              - path: /var/lib/nginx/tmp
                subPath: nginx_tmp
              - path: /tmp
                subPath: tmp
