apiVersion: v1
kind: Secret
metadata:
    name: tandoor-secret
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:ch+ANbW/w1HuFTlkYDYdyXX/8bpVhEqy2HhQ1QgZ5gPawf+4HrVjQp/MpvQcqPYMHnM=,iv:KJJoxViX/CXmfEy5F7JJKaXbHD3JQjtBRanWqz2dt9M=,tag:mJr10sfHiT7qD6dbNp1Acw==,type:str]
    SOCIAL_PROVIDERS: ENC[AES256_GCM,data:Z4fSHyktkgS749icuynhEhWIrFYThyMsE85oEKDLF2F0nXCgn+6AVX4tMONp4Q==,iv:OOpfs/bAM6ri2b+T6jm5uGwHH1ERfiqDdjsBtZOWxwA=,tag:CIXf4ORlIKttnnzclaMQUQ==,type:str]
    SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:Ttt0KMH6AM+KdBJvheY/GfOy4J7dZ5EVt2N/pwaJgokSWsvL9wW4u8/yF+hIWZ7cEcXXpVI3G5ED2o0V+hbgqubpYVy/3Cdu5nDJeBldOdzsr1pUj+a0nNaP4M/jidBqngipn6Fc11wQFFzDBkT6NCKhOX6GNeNN84P2d0uBajkaHpHu+hJZHB76maYebtf1E4H3Eilg/B3apebpqBuufp0vd67d1raSMlX9d5KZpMFR/uUCLQkWybT4g+F7FFMETE8wT+UxGU6uymzfMZJQ13K6cw3MqTEq8wfFnKRJCaXgi1iO5iQS4OQZMacAGVWrbN6w43H4zR92MHfuaABaXQ==,iv:edo7dRmhqcUbl1lVBeZU+EAZAwTet754opOU8G4IsWk=,tag:uaeEyAfcpLonSlQJ83Ss/A==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK09JU3g2VGQ5RW92WktS
            K3VBOEdmTlUydzcwRlh0STAyS1MwTW82TENRClpNaFNBY28xVy85SVJjbFg3blBR
            Mmw2dVIyWWZ5Yng0SGQvU3BUZWo5eUEKLS0tIFI4S3BSY3ZpYnhtdmtNU21QeWV2
            Ly83T1VTUlhuejZMOWJnYm5lYyt0QTgKHnjJMR//EJRwU81sn43KnMiLWDP3eMix
            BH00hG3ADTn0g1eWDN1g0m2k63xrp07RLNC7y5YO3Ti8bpeEax0WCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T23:22:22Z"
    mac: ENC[AES256_GCM,data:BjVtuRXlqc1uYmtnAy9d63yc1slbw1cMfMPH6GW2AUZbKc25OP/yjpLd3JouQ8a8nIAZLnc5I6it55X6aW3iwG5cwSdWXXquJJIKyvCLgEVjyosTeVa+bRcs1ZSpUEI5PGl+Uw+LbgnKSHnG3tx+V2rA7eWHVrxjOCiV0d8vpX8=,iv:0+TEgk6rnSHK0+gM+xmpUIR+9n55jfu+7fgc3/VyLCo=,tag:GIyynWDRgj36kn9gIMaP0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: tandoor-db-secrets
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:cKT55cBbPQ==,iv:dyUE6RVBRqdglkoBSpLf7B9vnYO0VBlp45siSgtWy6o=,tag:oHdA494tjr0BtAVzv6YTNg==,type:str]
    password: ENC[AES256_GCM,data:OjkXH0Z85w1tBw/+rp3fYlAJfLw1zgjZa0CeWpdr9CYH3dUD+oQEwK2GY971V8E26RwE9m5VP3Lt9okIGU4=,iv:xXB3FEq4V4VE8AsxWRa5G2grfTxUPQXDmYJiyNSUrY4=,tag:GwAaVS0UVCNFbHH7/JmVjw==,type:str]
sops:
    age:
        - recipient: age1yqc8cmp2x5w4n7w4y7375wt7j6cudm0czan6x3yt2l442hmufqzsrf20ud
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK09JU3g2VGQ5RW92WktS
            K3VBOEdmTlUydzcwRlh0STAyS1MwTW82TENRClpNaFNBY28xVy85SVJjbFg3blBR
            Mmw2dVIyWWZ5Yng0SGQvU3BUZWo5eUEKLS0tIFI4S3BSY3ZpYnhtdmtNU21QeWV2
            Ly83T1VTUlhuejZMOWJnYm5lYyt0QTgKHnjJMR//EJRwU81sn43KnMiLWDP3eMix
            BH00hG3ADTn0g1eWDN1g0m2k63xrp07RLNC7y5YO3Ti8bpeEax0WCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T23:22:22Z"
    mac: ENC[AES256_GCM,data:BjVtuRXlqc1uYmtnAy9d63yc1slbw1cMfMPH6GW2AUZbKc25OP/yjpLd3JouQ8a8nIAZLnc5I6it55X6aW3iwG5cwSdWXXquJJIKyvCLgEVjyosTeVa+bRcs1ZSpUEI5PGl+Uw+LbgnKSHnG3tx+V2rA7eWHVrxjOCiV0d8vpX8=,iv:0+TEgk6rnSHK0+gM+xmpUIR+9n55jfu+7fgc3/VyLCo=,tag:GIyynWDRgj36kn9gIMaP0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
