---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted

components:
  - ../../components/common

resources:
  - ./namespace.yaml
  - ./home-assistant/ks.yaml
  - ./mosquitto/ks.yaml
  - ./paperless/ks.yaml
  - ./vaultwarden/ks.yaml
  - ./zigbee2mqtt/ks.yaml
