---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./certificates.yaml
  - ./envoy.yaml
  - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./observability.yaml
