---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app jellyfin
spec:
  dependsOn:
    - name: intel-gpu-resource-driver
      namespace: kube-system
  interval: 1h
  path: ./kubernetes/home/apps/media/jellyfin/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: volsync-kopia-secret
        kind: Secret
    substitute:
      APP: *app
      VOLSYNC_CLAIM: jellyfin-data
      VOLSYNC_CAPACITY: 50Gi
      VOLSYNC_GID: "2000"
      VOLSYNC_UID: "2000"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
