---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${VOLSYNC_CLAIM}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: ${VOLSYNC_CAPACITY}
  storageClassName: local-hostpath

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-downloads
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Ti
  storageClassName: local-hostpath

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-incomplete
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Ti
  storageClassName: local-hostpath
