---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted

components:
  - ../../components/common

resources:
  - ./namespace.yaml
  - ./freshrss/ks.yaml
  - ./it-tools/ks.yaml
  #- ./headscale/ks.yaml
  - ./mollysocket/ks.yaml
  - ./mytabs/ks.yaml
  #- ./nextcloud/ks.yaml
  - ./ntfy/ks.yaml
  - ./tandoor/ks.yaml
  - ./zola-blog/ks.yaml
