---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted

resources:
  - ./database.yaml
  - ./dragonfly.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
  - ./secrets.sops.yaml
